# Generated by Django 5.0.1 on 2024-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
        migrations.AddField(
            model_name='login',
            name='number',
            field=models.CharField(default='', max_length=50, verbose_name=''),
        ),
        migrations.AddField(
            model_name='login',
            name='salary',
            field=models.CharField(default='', max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
    ]
